version: '3.1'

services:

  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/app:/usr/local/apache2/htdocs/app
    depends_on:
      - db
    networks:
      - pr_gr

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - pr_gr

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj_grupowy
    ports: 
      - "3306:3306"
    command:
      --secure-file-priv=""
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"
    networks:
      - pr_gr

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    networks:
      - pr_gr
networks:
  pr_gr:

volumes:
  mysql-data:

