version: '3.1'

services:

  db:
    container_name: mysql-grupowy
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj_grupowy
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    networks:
      - pr_gr
  
  panel:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8081:80"

# volumes:
  # mysql-db-grupowy:
