version: '3.1'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj_grupowy
    ports: 
      - "3306:3306"
    command:
      --secure-file-priv=""
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"
    networks:
      - pr_gr

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    networks:
      - pr_gr

networks:
  pr_gr:

volumes:
  mysql-data: