version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - pr_gr

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj_grupowy
    ports: 
      - "3306:3306"
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
      # - "mysql-db-grupowy:/var/lib/mysql"
    networks:
      - pr_gr
  
  panel:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    networks:
      - pr_gr

networks:
  pr_gr:
# volumes:
  # mysql-db-grupowy:
